### PR TITLE
Apple Main-Page

### PR DESCRIPTION
**Pull request by FrancoRosa**
- A first stable version of Apple web - Clone, _main-page_ ready to merge to master branch.
- Every image on _image_ folder

### CODE REVIEW

**Review by rOluochKe — CHANGES_REQUESTED** [review]
Hello @FrancoRosa 
### Good job so far :clap: However, you have issues to solve before your project could be approved.
- Remove the horizontal scroll in your page
- The order in which you call your css should be, your customed css to be called last after font-awesome and font
order of css
### Make these changes and resubmit for another code review. Good luck.
- For assistance, contact me on slack @iamraymond @rOluochKe
- Happy coding!

**Comment by FrancoRosa** [comment]
>     * e order in which you call your css should be, your customed css to be called l

Hello @rOluochKe 
Thank you for your kind review
The suggested changes where already made

**Review by kobiyoyo — APPROVED** [review]
## Hi @FrancoRosa       
#### Project Approved, but there are a few more things required. 
## Optional Changes:
#### Middle
- [x] These elements should be links

- [x] Align the footer to look like the original & give  space  to the top.


*Happy coding*

**Comment by FrancoRosa** [comment]
Hello @kobiyoyo!
I Made the requested changes, thank you for your review

image

**Pull request merged**
